"""Shared workbench planning controls and local-only program staging."""

from pathlib import Path
from uuid import uuid4

from kivy.clock import Clock
from kivy.core.window import Window
from kivy.metrics import dp
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.popup import Popup
from kivy.uix.scrollview import ScrollView

from carveracontroller.desktop_components import MUTED, Action, Choice, Field, QuantityField, Surface, label


def stage_program(workspace, text, name):
    """Open generated bytes through the same local viewer used by the file browser."""
    if workspace.app.state not in ("Idle", "N/A") or workspace.app.playing:
        raise ValueError("Pause planning preview changes until the machine is idle and playback has stopped")
    if workspace.machine.loading_file:
        raise ValueError("Wait for the current program preview to finish loading")
    data = text.encode("utf-8")
    if not data or len(data) > 16 * 1024 * 1024:
        raise ValueError("Generated program must be nonempty and smaller than 16 MB")
    directory = Path.home() / ".carvera" / "jobs" / "generated"
    directory.mkdir(parents=True, exist_ok=True)
    safe_name = "".join(c for c in name if c.isalnum() or c in "-_")[:60] or "plan"
    path = directory / f"{safe_name}-{uuid4().hex}.cnc"
    with path.open("xb") as stream:
        stream.write(data)
    workspace.machine.file_popup.local_rv.curr_selected_file = str(path)
    workspace.machine.view_local_file()
    return path


def planning_field(container, title, default="", quantity=None, **kwargs):
    cell = BoxLayout(orientation="vertical", spacing=dp(3), size_hint_y=None, height=dp(78 if quantity else 62))
    cell.add_widget(label(title, 10, MUTED, 21))
    field = (
        QuantityField(kind=quantity, text=str(default), **kwargs) if quantity else Field(text=str(default), **kwargs)
    )
    cell.add_widget(field)
    container.add_widget(cell)
    return field


def planning_choice(container, title, values, text=None):
    cell = BoxLayout(orientation="vertical", spacing=dp(3), size_hint_y=None, height=dp(62))
    cell.add_widget(label(title, 10, MUTED, 21))
    choice = Choice(text=text or values[0], values=values)
    cell.add_widget(choice)
    container.add_widget(cell)
    return choice


def planning_popup(title, body, width=0.8):
    """Fit draft forms to their fields, with scrolling on smaller windows."""
    body.size_hint_y = None
    body.bind(minimum_height=body.setter("height"))
    scroll = ScrollView(do_scroll_x=False)
    scroll.add_widget(body)
    popup = Popup(title=title, content=scroll, size_hint=(width, None), height=dp(400))

    def fit(*_):
        popup.height = min(Window.height * 0.9, body.minimum_height + dp(100))

    body.bind(minimum_height=fit)
    Window.bind(size=fit)
    popup.bind(on_dismiss=lambda *_: Window.unbind(size=fit))
    fit()
    return popup


class PlanningCard(Surface):
    """Content-sized disclosure: collapsed tools don't consume the viewing area."""

    def __init__(self, title, **kwargs):
        super().__init__(orientation="vertical", padding=dp(10), spacing=dp(6), size_hint_y=None, **kwargs)
        self.bind(minimum_height=self.setter("height"))
        self.title = title
        self.expanded = False
        self.header = Action("+  " + title, self.toggle, height=dp(34))
        self.add_widget(self.header)
        self.content = BoxLayout(orientation="vertical", spacing=dp(7), size_hint_y=None, height=0)
        self.content.bind(minimum_height=self.content.setter("height"))
        self.note = label(
            "Local planning only · review travel, offsets and physical tooling before execution.", 11, MUTED, 60
        )

    def toggle(self):
        self.expanded = not self.expanded
        self.header.text = ("−  " if self.expanded else "+  ") + self.title
        if self.expanded:
            self.add_widget(self.content)
        else:
            self.remove_widget(self.content)
        # Keep the disclosure heading in view after its height changes. Keeping
        # the old scroll fraction instead jumps to the end of a long form.
        Clock.schedule_once(lambda _dt: Clock.schedule_once(self._reveal_heading, 0), 0)

    def _reveal_heading(self, _dt):
        parent = self.parent
        while parent is not None:
            if isinstance(parent, ScrollView):
                parent.scroll_to(self.header, padding=dp(8), animate=False)
                return
            parent = parent.parent
