<AngleSettings>:
    ScrollView:
        do_scroll_x: False
        size_hint: 1,1
        bar_width: 4
        bar_inactive_color: [.7,.7,.7,.9]
        GridLayout:
            cols: 2
            size_hint_y: None
            height: self.minimum_height
            spacing:dp(2)
            row_default_height: dp(28)
            row_force_default: True
            padding:dp(1)
            halign:'right'
            valign:'top'

            BoxLayout:
                ProbeSettingLabel:
                    label_text: 'X :'
                ToolTipTextInput:
                    id: XAxisDistance
                    size_hint_x: 0.4
                    font_size: '14dp'
                    hint_text: tr._("required")
					hint_text_color: (0.2,0.5,0.5,0.5)
                    tooltip_txt: tr._('Distance between probe points on X axis')
                    tooltip_image: ''
                    multiline: False
                    halign:'right'
                    input_type: 'number'
                    input_filter: 'float'
                    text: root.get_setting('XAxisDistance')
                    on_text: root.setting_changed('XAxisDistance', self.text)

            BoxLayout:
                ProbeSettingLabel:
                    label_text: 'Y :'
                ToolTipTextInput:
                    id: YAxisDistance
                    size_hint_x: 0.4
                    font_size: '14dp'
                    hint_text: tr._("required")
					hint_text_color: (0.2,0.5,0.5,0.5)
                    tooltip_txt: tr._('Distance between probe points on Y axis')
                    tooltip_image: ''
                    multiline: False
                    halign:'right'
                    input_type: 'number'
                    input_filter: 'float'
                    text: root.get_setting('YAxisDistance')
                    on_text: root.setting_changed('YAxisDistance', self.text)
            BoxLayout:
                ProbeSettingLabel:
                    label_text: 'Probe Depth (E)'
                ToolTipTextInput:
                    id: ProbeDepth
                    size_hint_x: 0.4
                    font_size: '14dp'
                    hint_text: tr._("2")
					hint_text_color: (0.2,0.5,0.5,0.5)
                    tooltip_txt: tr._('Distance along secondary axis to probe')
                    tooltip_image: ''
                    multiline: False
                    halign:'right'
                    input_type: 'number'
                    input_filter: 'float'
                    text: root.get_setting('ProbeDepth')
                    on_text: root.setting_changed('ProbeDepth', self.text)
            BoxLayout:
                ProbeSettingLabel:
                    label_text: 'Tip Dia (D):'
                ToolTipTextInput:
                    id: ProbeTipDiameter
                    size_hint_x: 0.4
                    font_size: '14dp'
                    hint_text: tr._("config")
					hint_text_color: (0.2,0.5,0.5,0.5)
                    tooltip_txt: tr._('Effective Diameter of Probe Tip. Measure with M460')
                    tooltip_image: 'addons/probing/data/icons_1024x768/general_parameters/probe_parameter_d.png'
                    tooltip_image_size: 200,200
                    multiline: False
                    halign:'right'
                    input_type: 'number'
                    input_filter: 'float'
                    text: root.get_setting('ProbeTipDiameter')
                    on_text: root.setting_changed('ProbeTipDiameter', self.text)
            BoxLayout:
                ProbeSettingLabel:
                    label_text: 'Pocket Depth (H):'
                ToolTipTextInput:
                    id: PocketProbeDepth
                    size_hint_x: 0.4
                    font_size: '14dp'
                    hint_text: tr._("0")
					hint_text_color: (0.2,0.5,0.5,0.5)
                    tooltip_txt: tr._('Distance to probe straight down before performing remainder of probing operations')
                    tooltip_image: ''
                    multiline: False
                    halign:'right'
                    input_type: 'number'
                    input_filter: 'float'
                    text: root.get_setting('PocketProbeDepth')
                    on_text: root.setting_changed('PocketProbeDepth', self.text)
            BoxLayout:
                ProbeSettingLabel:
                    label_text: 'Feed Rate (F):'
                ToolTipTextInput:
                    id: FastFeedRate
                    size_hint_x: 0.4
                    font_size: '14dp'
                    hint_text: tr._("300")
					hint_text_color: (0.2,0.5,0.5,0.5)
                    tooltip_txt: tr._('Optional probing feed rate override')
                    tooltip_image: ''
                    multiline: False
                    halign:'right'
                    input_type: 'number'
                    input_filter: 'float'
                    text: root.get_setting('FastFeedRate')
                    on_text: root.setting_changed('FastFeedRate', self.text)
            BoxLayout:
                ProbeSettingLabel:
                    label_text: 'Rapid (K):'
                ToolTipTextInput:
                    id: RapidFeedRate
                    size_hint_x: 0.4
                    font_size: '14dp'
                    hint_text: tr._("800")
					hint_text_color: (0.2,0.5,0.5,0.5)
                    tooltip_txt: tr._('Optional rapid feed rate override')
                    tooltip_image: ''
                    multiline: False
                    halign:'right'
                    input_type: 'number'
                    input_filter: 'float'
                    text: root.get_setting('RapidFeedRate')
                    on_text: root.setting_changed('RapidFeedRate', self.text)
            BoxLayout:
                ProbeSettingLabel:
                    label_text: 'Repeat (L):'
                ToolTipTextInput:
                    id: RepeatOperationCount
                    size_hint_x: 0.4
                    font_size: '14dp'
                    hint_text: tr._("0")
					hint_text_color: (0.2,0.5,0.5,0.5)
                    tooltip_txt: tr._('Number of times to repeat the probing operation')
                    tooltip_image: ''
                    multiline: False
                    halign:'right'
                    input_type: 'number'
                    input_filter: 'float'
                    text: root.get_setting('RepeatOperationCount')
                    on_text: root.setting_changed('RepeatOperationCount', self.text)
            BoxLayout:
                ProbeSettingLabel:
                    label_text: 'Edge Retract (R):'
                ToolTipTextInput:
                    id: EdgeRetractDistance
                    size_hint_x: 0.4
                    font_size: '14dp'
                    hint_text: tr._("1.5")
					hint_text_color: (0.2,0.5,0.5,0.5)
                    tooltip_txt: tr._('Distance away from surface to retract before double tapping the probe')
                    tooltip_image: ''
                    multiline: False
                    halign:'right'
                    input_type: 'number'
                    input_filter: 'float'
                    text: root.get_setting('EdgeRetractDistance')
                    on_text: root.setting_changed('EdgeRetractDistance', self.text)
            BoxLayout:
                ProbeSettingLabel:
                    label_text: 'Btm Retract (C):'
                ToolTipTextInput:
                    id: BottomSurfaceRetract
                    size_hint_x: 0.4
                    font_size: '14dp'
                    hint_text: tr._("2")
					hint_text_color: (0.2,0.5,0.5,0.5)
                    tooltip_txt: tr._('If Pocket Depth is enabled, how far above the surface to raise before continuing the operation')
                    tooltip_image: ''
                    multiline: False
                    halign:'right'
                    input_type: 'number'
                    input_filter: 'float'
                    text: root.get_setting('BottomSurfaceRetract')
                    on_text: root.setting_changed('BottomSurfaceRetract', self.text)
            BoxLayout:
                ProbeSettingLabel:
                    label_text: 'Angle (Q):'
                ToolTipTextInput:
                    size_hint_x: 0.4
                    font_size: '14dp'
                    hint_text: tr._("0")
					hint_text_color: (0.2,0.5,0.5,0.5)
                    tooltip_txt: tr._('Degrees to rotate the XY coordinate plane when probing.')
                    tooltip_image: 'addons/probing/data/icons_1024x768/angle/probe_angle_arbitrary_negative.png'
                    tooltip_image_size: 200,200
                    multiline: False
                    halign:'right'
                    input_type: 'number'
                    input_filter: 'float'
                    text: root.get_setting('QAngle')
                    on_text: root.setting_changed('QAngle', self.text)
            BoxLayout:
                ProbeSettingLabel:
                    label_text: 'V Visualize:'
                ToolTipTextInput:
                    id: VisualizeDistance
                    size_hint_x: 0.4
                    font_size: '14dp'
                    hint_text: tr._("0")
					hint_text_color: (0.2,0.5,0.5,0.5)
                    tooltip_txt: tr._('If set, the probe will trace the probed angle after the operation finishes')
                    tooltip_image: ''
                    multiline: False
                    halign:'right'
                    input_type: 'number'
                    input_filter: 'float'
                    text: root.get_setting('VisualizeDistance')
                    on_text: root.setting_changed('VisualizeDistance', self.text)
            BoxLayout:
                ProbeSettingLabel:
                    label_text: 'S Set WCS Rotation:'
                    hint_text: 'Set WCS Rotation'
                ToolTipSwitch:
                    id: SaveRotation
                    size_hint_x: 0.4
                    tooltip_txt: tr._('This switch will set your current WCS rotation to the probed rotation angle')
                    canvas.before:
                        Color:
                            rgba: 50/255, 50/255, 50/255, 1
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    active: root.get_setting('SaveRotation') == "1"
                    on_active: root.setting_changed('SaveRotation', "1" if self.active else "0")
            BoxLayout:
                ProbeSettingLabel:
                    label_text: 'Normally Closed (I):'
                    hint_text: ''
                ToolTipSwitch:
                    id: UseProbeNormallyClosed
                    size_hint_x: 0.4
                    font_size: '14dp'
                    tooltip_txt: tr._('Enable this switch if you have a normally closed probe instead of a normally open one')
                    canvas.before:
                        Color:
                            rgba: 50/255, 50/255, 50/255, 1
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    active: root.get_setting('UseProbeNormallyClosed') == "1"
                    on_active: root.setting_changed('UseProbeNormallyClosed', "1" if self.active else "0")
            BoxLayout:
                ProbeSettingLabel:
                    label_text: 'More Info:'
                    hint_text: ''
                BoxLayout:
                    size_hint_x: 0.4
                    HelpButton:
                        helpPath: "https://carvera-community.gitbook.io/docs/controller/features/wcs-rotation#clearing-a-rotation"